
/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Find the total customers by country

select
country,
count(*) as total_customer
from gold.dim_customer
group by country;

-- Find the customer by gender

select 
gender,
count(*) as total_customer
from gold.dim_customer
group by gender;


-- Find total products by category

select 
category,
COUNT(product_name) as total_prof
from gold.dim_products
group by category


-- What is the average costs in each category?

select 
category,
avg(cost) as avg_cost
from gold.dim_products
group by category


-- What is the total revenue generated for each category?

select 
p.category,
sum(f.sales_amount) as Total_revenue
from gold.fact_sales as f
left join gold.dim_products as p
on f.product_key = p.Product_key
group by p.category



-- What is the total revenue generated by each customer?

select 
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_customer as c
on f.customer_key = c.customer_key
group by c.customer_key , c.first_name , c.last_name
order by total_revenue desc;


-- What is the distribution of sold items across countries?

select 
c.country,
sum(f.quantity) as total_distribution
from gold.fact_sales as f
left join gold.dim_customer as c
on f.customer_key = c.customer_key
group by c.country
order by  total_distribution desc;
